// <auto-generated />
using System;
using INF27507_Boutique_En_Ligne;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace INF27507_Boutique_En_Ligne.Migrations
{
    [DbContext(typeof(BoutiqueDbContext))]
    [Migration("20220314192809_Champs-Produit-Nullable")]
    partial class ChampsProduitNullable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("INF27507_Boutique_En_Ligne.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("pk_carts_id");

                    b.HasIndex("ClientId");

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("INF27507_Boutique_En_Ligne.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<double>("SalePrice")
                        .HasColumnType("double");

                    b.HasKey("Id")
                        .HasName("pk_cartitems_id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("INF27507_Boutique_En_Ligne.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id")
                        .HasName("pk_categories_id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Apparel"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Footwear"
                        });
                });

            modelBuilder.Entity("INF27507_Boutique_En_Ligne.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Balance")
                        .HasColumnType("double");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id")
                        .HasName("pk_clients_id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 250.0,
                            Firstname = "Default",
                            Lastname = "User",
                            Username = "Default-User"
                        });
                });

            modelBuilder.Entity("INF27507_Boutique_En_Ligne.Models.Colour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id")
                        .HasName("pk_colours_id");

                    b.ToTable("Colours");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Black"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Blue"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Yellow"
                        },
                        new
                        {
                            Id = 4,
                            Name = "White"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Green"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Pink"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Brown"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Red"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Olive"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Beige"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Silver"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Grey"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Peach"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Orange"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Gold"
                        });
                });

            modelBuilder.Entity("INF27507_Boutique_En_Ligne.Models.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id")
                        .HasName("pk_genders_id");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Boys"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Girls"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Men"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Women"
                        });
                });

            modelBuilder.Entity("INF27507_Boutique_En_Ligne.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("pk_orders_id");

                    b.HasIndex("CartId");

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("INF27507_Boutique_En_Ligne.Models.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id")
                        .HasName("pk_paymentmethods_id");

                    b.ToTable("PaymentMethods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Credits"
                        },
                        new
                        {
                            Id = 2,
                            Name = "PayPal"
                        });
                });

            modelBuilder.Entity("INF27507_Boutique_En_Ligne.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ColourId")
                        .HasColumnType("int");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int");

                    b.Property<int>("SellerId")
                        .HasColumnType("int");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UsageId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("pk_products_id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ColourId");

                    b.HasIndex("GenderId");

                    b.HasIndex("ProductTypeId");

                    b.HasIndex("SellerId");

                    b.HasIndex("SubCategoryId");

                    b.HasIndex("UsageId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CategoryId = 1,
                            ColourId = 1,
                            GenderId = 1,
                            Image = "39855.jpg",
                            ImageURL = "http://assets.myntassets.com/v1/images/style/properties/6fa45d21a0d6194932652bfcaf4c0e2b_images.jpg",
                            Price = 20.0,
                            ProductTypeId = 1,
                            SellerId = 1,
                            SubCategoryId = 1,
                            Title = "Gini and Jony Boys Printed Black T-Shirt",
                            UsageId = 1
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CategoryId = 1,
                            ColourId = 2,
                            GenderId = 1,
                            Image = "35881.jpg",
                            ImageURL = "http://assets.myntassets.com/v1/images/style/properties/2ea8c6ea0765fca46041647c5ce1c514_images.jpg",
                            Price = 10.75,
                            ProductTypeId = 1,
                            SellerId = 1,
                            SubCategoryId = 1,
                            Title = "Jungle Book Boys Jungle Friends Blue T-shirt",
                            UsageId = 1
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            CategoryId = 1,
                            ColourId = 3,
                            GenderId = 1,
                            Image = "39859.jpg",
                            ImageURL = "http://assets.myntassets.com/v1/images/style/properties/a3c0711f3d54240e227c7c615d8d46c5_images.jpg",
                            Price = 20.0,
                            ProductTypeId = 1,
                            SellerId = 1,
                            SubCategoryId = 1,
                            Title = "Palm Tree Boys Printed Yellow T-Shirt",
                            UsageId = 1
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            CategoryId = 1,
                            ColourId = 4,
                            GenderId = 2,
                            Image = "2700.jpg",
                            ImageURL = "http://assets.myntassets.com/v1/images/style/properties/d2c388bcd6a795e0d0cea56392d352a6_images.jpg",
                            Price = 49.990000000000002,
                            ProductTypeId = 2,
                            SellerId = 1,
                            SubCategoryId = 1,
                            Title = "Disney Kids Girl's White Kidswear",
                            UsageId = 1
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            CategoryId = 1,
                            ColourId = 5,
                            GenderId = 2,
                            Image = "18171.jpg",
                            ImageURL = "http://assets.myntassets.com/v1/images/style/properties/f1dbb13abb1efd3ba19bd4108f1a6703_images.jpg",
                            Price = 15.5,
                            ProductTypeId = 2,
                            SellerId = 1,
                            SubCategoryId = 1,
                            Title = "Doodle Kids Girls Ballon Green Top",
                            UsageId = 1
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            CategoryId = 1,
                            ColourId = 2,
                            GenderId = 2,
                            Image = "34148.jpg",
                            ImageURL = "http://assets.myntassets.com/v1/images/style/properties/c90319b0bf114581aa3dc692239a0607_images.jpg",
                            Price = 20.0,
                            ProductTypeId = 3,
                            SellerId = 1,
                            SubCategoryId = 2,
                            Title = "Gini and Jony Girls Washed Blue Skirt",
                            UsageId = 1
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            CategoryId = 2,
                            ColourId = 1,
                            GenderId = 3,
                            Image = "54529.jpg",
                            ImageURL = "http://assets.myntassets.com/v1/images/style/properties/F-Sports-Men-Black-Shoes_f4920f8c2dd4277191a4468e5acf397d_images.jpg",
                            Price = 10.0,
                            ProductTypeId = 5,
                            SellerId = 1,
                            SubCategoryId = 3,
                            Title = "F Sports Men Black Shoes",
                            UsageId = 1
                        },
                        new
                        {
                            Id = 8,
                            Active = true,
                            CategoryId = 2,
                            ColourId = 1,
                            GenderId = 3,
                            Image = "13072.jpg",
                            ImageURL = "http://assets.myntassets.com/v1/images/style/properties/2fc766a7415035d5855a236326c01366_images.jpg",
                            Price = 15.0,
                            ProductTypeId = 5,
                            SellerId = 1,
                            SubCategoryId = 3,
                            Title = "Numero Uno Men Black Casual Shoes",
                            UsageId = 1
                        },
                        new
                        {
                            Id = 9,
                            Active = true,
                            CategoryId = 2,
                            ColourId = 1,
                            GenderId = 3,
                            Image = "13080.jpg",
                            ImageURL = "http://assets.myntassets.com/v1/images/style/properties/efef30c05460e90a1e170998dde8f92c_images.jpg",
                            Price = 15.0,
                            ProductTypeId = 5,
                            SellerId = 1,
                            SubCategoryId = 3,
                            Title = "Numero Uno Men Black Casual Shoes",
                            UsageId = 1
                        },
                        new
                        {
                            Id = 10,
                            Active = true,
                            CategoryId = 2,
                            ColourId = 1,
                            GenderId = 4,
                            Image = "56943.jpg",
                            ImageURL = "http://assets.myntassets.com/v1/images/style/properties/HM-Women-Black-Sandals_a9da5e1e341b17a3eb061f783c01ca21_images.jpg",
                            Price = 49.990000000000002,
                            ProductTypeId = 7,
                            SellerId = 1,
                            SubCategoryId = 3,
                            Title = "HM Women Black Sandals",
                            UsageId = 1
                        },
                        new
                        {
                            Id = 11,
                            Active = true,
                            CategoryId = 2,
                            ColourId = 6,
                            GenderId = 4,
                            Image = "45324.jpg",
                            ImageURL = "http://assets.myntassets.com/v1/images/style/properties/31414b116179349f43cf4a558a05de25_images.jpg",
                            Price = 49.990000000000002,
                            ProductTypeId = 8,
                            SellerId = 1,
                            SubCategoryId = 3,
                            Title = "Cobblerz Women Pink & White Wedges",
                            UsageId = 1
                        },
                        new
                        {
                            Id = 12,
                            Active = true,
                            CategoryId = 2,
                            ColourId = 7,
                            GenderId = 4,
                            Image = "10292.jpg",
                            ImageURL = "http://assets.myntassets.com/v1/images/style/properties/Clarks-Women-Dolphin-Splash-Leather-Silver-Sandals_e55a6fa02cca3f6b6f3fa750619911d4_images.jpg",
                            Price = 55.75,
                            ProductTypeId = 8,
                            SellerId = 1,
                            SubCategoryId = 3,
                            Title = "Clarks Women Brown Leather Heels",
                            UsageId = 1
                        },
                        new
                        {
                            Id = 13,
                            Active = true,
                            CategoryId = 1,
                            ColourId = 8,
                            GenderId = 1,
                            Image = "38249.jpg",
                            ImageURL = "http://assets.myntassets.com/v1/images/style/properties/91b690cee7977353b5fa29ae56bf22d4_images.jpg",
                            Price = 10.0,
                            ProductTypeId = 1,
                            SellerId = 2,
                            SubCategoryId = 1,
                            Title = "Ben 10 Boys Red Printed T-shirt",
                            UsageId = 1
                        },
                        new
                        {
                            Id = 14,
                            Active = true,
                            CategoryId = 1,
                            ColourId = 9,
                            GenderId = 1,
                            Image = "15571.jpg",
                            ImageURL = "http://assets.myntassets.com/v1/images/style/properties/ba3659da8365d5f255ab9b992fec690f_images.jpg",
                            Price = 49.990000000000002,
                            ProductTypeId = 1,
                            SellerId = 2,
                            SubCategoryId = 1,
                            Title = "Chhota Bheem Kids Boys Spare Me TShirt",
                            UsageId = 1
                        },
                        new
                        {
                            Id = 15,
                            Active = true,
                            CategoryId = 1,
                            ColourId = 5,
                            GenderId = 1,
                            Image = "39861.jpg",
                            ImageURL = "http://assets.myntassets.com/v1/images/style/properties/f61e63af58565cb07fba8b5d54db3994_images.jpg",
                            Price = 55.75,
                            ProductTypeId = 1,
                            SellerId = 2,
                            SubCategoryId = 1,
                            Title = "Gini and Jony Boys Polo Green T-Shirt",
                            UsageId = 1
                        },
                        new
                        {
                            Id = 16,
                            Active = true,
                            CategoryId = 1,
                            ColourId = 6,
                            GenderId = 2,
                            Image = "38766.jpg",
                            ImageURL = "http://assets.myntassets.com/v1/images/style/properties/9097ddc9c0e1272023976f8e8da00617_images.jpg",
                            Price = 30.850000000000001,
                            ProductTypeId = 9,
                            SellerId = 2,
                            SubCategoryId = 2,
                            Title = "Gini and Jony Girls Pink Shorts",
                            UsageId = 1
                        },
                        new
                        {
                            Id = 17,
                            Active = true,
                            CategoryId = 1,
                            ColourId = 8,
                            GenderId = 2,
                            Image = "35448.jpg",
                            ImageURL = "http://assets.myntassets.com/v1/images/style/properties/bdcb051154afdf6da0a6b1010e116c35_images.jpg",
                            Price = 15.5,
                            ProductTypeId = 2,
                            SellerId = 2,
                            SubCategoryId = 1,
                            Title = "Doodle Girls Printed Red Top",
                            UsageId = 1
                        },
                        new
                        {
                            Id = 18,
                            Active = true,
                            CategoryId = 1,
                            ColourId = 6,
                            GenderId = 2,
                            Image = "24941.jpg",
                            ImageURL = "http://assets.myntassets.com/v1/images/style/properties/c1a5e415fd0e4f4945aa965729de43c1_images.jpg",
                            Price = 15.0,
                            ProductTypeId = 2,
                            SellerId = 2,
                            SubCategoryId = 1,
                            Title = "United Colors of Benetton Kids Girls Pink Top",
                            UsageId = 1
                        },
                        new
                        {
                            Id = 19,
                            Active = true,
                            CategoryId = 2,
                            ColourId = 4,
                            GenderId = 3,
                            Image = "40785.jpg",
                            ImageURL = "http://assets.myntassets.com/v1/images/style/properties/3ac1a2f48ba5767e13a5cb112da62654_images.jpg",
                            Price = 15.5,
                            ProductTypeId = 10,
                            SellerId = 2,
                            SubCategoryId = 4,
                            Title = "Quiksilver Men White Flip Flops",
                            UsageId = 1
                        },
                        new
                        {
                            Id = 20,
                            Active = true,
                            CategoryId = 2,
                            ColourId = 2,
                            GenderId = 3,
                            Image = "26553.jpg",
                            ImageURL = "http://assets.myntassets.com/v1/images/style/properties/a02747a571130ca2d2aa6f491d8b5fc2_images.jpg",
                            Price = 15.0,
                            ProductTypeId = 5,
                            SellerId = 2,
                            SubCategoryId = 3,
                            Title = "ID Men Blue Shoes",
                            UsageId = 1
                        },
                        new
                        {
                            Id = 21,
                            Active = true,
                            CategoryId = 2,
                            ColourId = 1,
                            GenderId = 3,
                            Image = "45603.jpg",
                            ImageURL = "http://assets.myntassets.com/v1/images/style/properties/8f3b9f4c5f554e39681567b22985966e_images.jpg",
                            Price = 20.0,
                            ProductTypeId = 4,
                            SellerId = 2,
                            SubCategoryId = 3,
                            Title = "Arrow Men Black Formal Shoes",
                            UsageId = 2
                        },
                        new
                        {
                            Id = 22,
                            Active = true,
                            CategoryId = 2,
                            ColourId = 10,
                            GenderId = 4,
                            Image = "45322.jpg",
                            ImageURL = "http://assets.myntassets.com/v1/images/style/properties/04bf5738b8d46cc9a768caf2a35f9451_images.jpg",
                            Price = 15.5,
                            ProductTypeId = 8,
                            SellerId = 2,
                            SubCategoryId = 3,
                            Title = "Cobblerz Women Beige & Blue Wedges",
                            UsageId = 1
                        },
                        new
                        {
                            Id = 23,
                            Active = true,
                            CategoryId = 2,
                            ColourId = 11,
                            GenderId = 4,
                            Image = "41669.jpg",
                            ImageURL = "http://assets.myntassets.com/v1/images/style/properties/a87cc5ed84c4882d76413571787cad2f_images.jpg",
                            Price = 10.0,
                            ProductTypeId = 8,
                            SellerId = 2,
                            SubCategoryId = 3,
                            Title = "Catwalk Women Silver Heels",
                            UsageId = 1
                        },
                        new
                        {
                            Id = 24,
                            Active = true,
                            CategoryId = 2,
                            ColourId = 2,
                            GenderId = 4,
                            Image = "7595.jpg",
                            ImageURL = "http://assets.myntassets.com/v1/images/style/properties/b3f3d37c936ee1b487eb6ed3ef399e0b_images.jpg",
                            Price = 30.850000000000001,
                            ProductTypeId = 6,
                            SellerId = 2,
                            SubCategoryId = 3,
                            Title = "Nike Women Ten Blue White Shoe",
                            UsageId = 3
                        },
                        new
                        {
                            Id = 25,
                            Active = true,
                            CategoryId = 1,
                            ColourId = 6,
                            GenderId = 1,
                            Image = "46831.jpg",
                            ImageURL = "http://assets.myntassets.com/v1/images/style/properties/943d9b272c042d8b06ee6b1d277de5be_images.jpg",
                            Price = 30.0,
                            ProductTypeId = 16,
                            SellerId = 3,
                            SubCategoryId = 1,
                            Title = "Gini and Jony Boys Pink Shirt",
                            UsageId = 1
                        },
                        new
                        {
                            Id = 26,
                            Active = true,
                            CategoryId = 1,
                            ColourId = 2,
                            GenderId = 1,
                            Image = "30720.jpg",
                            ImageURL = "http://assets.myntassets.com/v1/images/style/properties/e95357480c6acea8e7bcdce602a0a532_images.jpg",
                            Price = 10.0,
                            ProductTypeId = 11,
                            SellerId = 3,
                            SubCategoryId = 1,
                            Title = "Fabindia Boys Printed Blue Kurta",
                            UsageId = 4
                        },
                        new
                        {
                            Id = 27,
                            Active = true,
                            CategoryId = 1,
                            ColourId = 5,
                            GenderId = 1,
                            Image = "40974.jpg",
                            ImageURL = "http://assets.myntassets.com/v1/images/style/properties/c534bd1e6aef81fafe5fddf41bff6401_images.jpg",
                            Price = 15.0,
                            ProductTypeId = 1,
                            SellerId = 3,
                            SubCategoryId = 1,
                            Title = "Gini and Jony Boys United Green T-shirt",
                            UsageId = 1
                        },
                        new
                        {
                            Id = 28,
                            Active = true,
                            CategoryId = 1,
                            ColourId = 6,
                            GenderId = 2,
                            Image = "42002.jpg",
                            ImageURL = "http://assets.myntassets.com/v1/images/style/properties/d07f3c84fe3df82e98b46ba9a55cc866_images.jpg",
                            Price = 15.5,
                            ProductTypeId = 12,
                            SellerId = 3,
                            SubCategoryId = 2,
                            Title = "Gini and Jony Girls Kinky Pink Capris",
                            UsageId = 1
                        },
                        new
                        {
                            Id = 29,
                            Active = true,
                            CategoryId = 1,
                            ColourId = 6,
                            GenderId = 2,
                            Image = "8359.jpg",
                            ImageURL = "http://assets.myntassets.com/v1/images/style/properties/705333ff633393a22cb5c229128afcc2_images.jpg",
                            Price = 30.850000000000001,
                            ProductTypeId = 1,
                            SellerId = 3,
                            SubCategoryId = 1,
                            Title = "Doodle Girl's Princess Cute Little Pink Kidswear",
                            UsageId = 1
                        },
                        new
                        {
                            Id = 30,
                            Active = true,
                            CategoryId = 1,
                            ColourId = 4,
                            GenderId = 2,
                            Image = "40972.jpg",
                            ImageURL = "http://assets.myntassets.com/v1/images/style/properties/6ad4e27d85073205cafdd1edbd1d86f6_images.jpg",
                            Price = 55.75,
                            ProductTypeId = 2,
                            SellerId = 3,
                            SubCategoryId = 1,
                            Title = "Palm Tree Girls Knits White Tops",
                            UsageId = 1
                        },
                        new
                        {
                            Id = 31,
                            Active = true,
                            CategoryId = 2,
                            ColourId = 4,
                            GenderId = 3,
                            Image = "23500.jpg",
                            ImageURL = "http://assets.myntassets.com/v1/images/style/properties/0734fd1f8aea4117ff2f3810a8d7d30b_images.jpg",
                            Price = 49.990000000000002,
                            ProductTypeId = 6,
                            SellerId = 3,
                            SubCategoryId = 3,
                            Title = "FILA Men Hostile White Sports Shoes",
                            UsageId = 3
                        },
                        new
                        {
                            Id = 32,
                            Active = true,
                            CategoryId = 2,
                            ColourId = 12,
                            GenderId = 3,
                            Image = "41455.jpg",
                            ImageURL = "http://assets.myntassets.com/v1/images/style/properties/788847bb37bf3ba404eeebcb290c8746_images.jpg",
                            Price = 19.989999999999998,
                            ProductTypeId = 13,
                            SellerId = 3,
                            SubCategoryId = 5,
                            Title = "Lee Cooper Men Grey Sandals",
                            UsageId = 1
                        },
                        new
                        {
                            Id = 33,
                            Active = true,
                            CategoryId = 2,
                            ColourId = 7,
                            GenderId = 3,
                            Image = "7364.jpg",
                            ImageURL = "http://assets.myntassets.com/v1/images/style/properties/e1f82da932e688fe0f59740369c59b97_images.jpg",
                            Price = 20.0,
                            ProductTypeId = 5,
                            SellerId = 3,
                            SubCategoryId = 3,
                            Title = "Red Tape Men's Brown casual Shoe",
                            UsageId = 1
                        },
                        new
                        {
                            Id = 34,
                            Active = true,
                            CategoryId = 2,
                            ColourId = 4,
                            GenderId = 4,
                            Image = "5319.jpg",
                            ImageURL = "http://assets.myntassets.com/v1/images/style/properties/54a68221353b667c1aa1c17631a6e534_images.jpg",
                            Price = 15.5,
                            ProductTypeId = 6,
                            SellerId = 3,
                            SubCategoryId = 3,
                            Title = "ADIDAS Women's Duramo Luxury White Shoe",
                            UsageId = 3
                        },
                        new
                        {
                            Id = 35,
                            Active = true,
                            CategoryId = 2,
                            ColourId = 1,
                            GenderId = 4,
                            Image = "54118.jpg",
                            ImageURL = "http://assets.myntassets.com/v1/images/style/properties/8d6fd53f28e010658cdf5c14c43d0cb0_images.jpg",
                            Price = 10.0,
                            ProductTypeId = 8,
                            SellerId = 3,
                            SubCategoryId = 3,
                            Title = "Rocia Women Black Flats",
                            UsageId = 1
                        },
                        new
                        {
                            Id = 36,
                            Active = true,
                            CategoryId = 2,
                            ColourId = 8,
                            GenderId = 4,
                            Image = "49608.jpg",
                            ImageURL = "http://assets.myntassets.com/v1/images/style/properties/5055777a92b6b46240d58dd31eb46ba8_images.jpg",
                            Price = 30.0,
                            ProductTypeId = 5,
                            SellerId = 3,
                            SubCategoryId = 3,
                            Title = "Catwalk Women Red Shoes",
                            UsageId = 1
                        },
                        new
                        {
                            Id = 37,
                            Active = true,
                            CategoryId = 1,
                            ColourId = 8,
                            GenderId = 1,
                            Image = "40956.jpg",
                            ImageURL = "http://assets.myntassets.com/v1/images/style/properties/a913999991c21e8233f1d5fd1ab20802_images.jpg",
                            Price = 10.0,
                            ProductTypeId = 1,
                            SellerId = 4,
                            SubCategoryId = 1,
                            Title = "Gini and Jony Boys Comics Red T-shirt",
                            UsageId = 1
                        },
                        new
                        {
                            Id = 38,
                            Active = true,
                            CategoryId = 1,
                            ColourId = 8,
                            GenderId = 1,
                            Image = "48250.jpg",
                            ImageURL = "http://assets.myntassets.com/v1/images/style/properties/edc6d691eeab51c01264064be592e390_images.jpg",
                            Price = 20.0,
                            ProductTypeId = 1,
                            SellerId = 4,
                            SubCategoryId = 1,
                            Title = "The Amazing Spiderman Boys Red T-Shirt",
                            UsageId = 1
                        },
                        new
                        {
                            Id = 39,
                            Active = true,
                            CategoryId = 1,
                            ColourId = 2,
                            GenderId = 1,
                            Image = "37524.jpg",
                            ImageURL = "http://assets.myntassets.com/v1/images/style/properties/1ed5e3016f7bf021add2fd67ac735d80_images.jpg",
                            Price = 24.989999999999998,
                            ProductTypeId = 15,
                            SellerId = 4,
                            SubCategoryId = 1,
                            Title = "Madagascar3 Infant Boys Light Blue Snapsuit Romper",
                            UsageId = 1
                        },
                        new
                        {
                            Id = 40,
                            Active = true,
                            CategoryId = 1,
                            ColourId = 8,
                            GenderId = 2,
                            Image = "35448.jpg",
                            ImageURL = "http://assets.myntassets.com/v1/images/style/properties/bdcb051154afdf6da0a6b1010e116c35_images.jpg",
                            Price = 15.5,
                            ProductTypeId = 2,
                            SellerId = 4,
                            SubCategoryId = 1,
                            Title = "Doodle Girls Printed Red Top",
                            UsageId = 1
                        },
                        new
                        {
                            Id = 41,
                            Active = true,
                            CategoryId = 1,
                            ColourId = 3,
                            GenderId = 2,
                            Image = "2701.jpg",
                            ImageURL = "http://assets.myntassets.com/v1/images/style/properties/9f0369e7d1bb5beabf1071dcd6f15867_images.jpg",
                            Price = 30.850000000000001,
                            ProductTypeId = 2,
                            SellerId = 4,
                            SubCategoryId = 1,
                            Title = "Disney Kids Girl's Yellow Daisy Kidswear",
                            UsageId = 1
                        },
                        new
                        {
                            Id = 42,
                            Active = true,
                            CategoryId = 1,
                            ColourId = 13,
                            GenderId = 2,
                            Image = "39835.jpg",
                            ImageURL = "http://assets.myntassets.com/v1/images/style/properties/a7e6fca57d133337f6e76e3b5e74fd20_images.jpg",
                            Price = 20.0,
                            ProductTypeId = 2,
                            SellerId = 4,
                            SubCategoryId = 1,
                            Title = "Gini and Jony Girls Printed Peach Top",
                            UsageId = 1
                        },
                        new
                        {
                            Id = 43,
                            Active = true,
                            CategoryId = 2,
                            ColourId = 9,
                            GenderId = 3,
                            Image = "11947.jpg",
                            ImageURL = "http://assets.myntassets.com/v1/images/style/properties/464879391de4e1a7b881dad3b7bd83a8_images.jpg",
                            Price = 24.989999999999998,
                            ProductTypeId = 13,
                            SellerId = 4,
                            SubCategoryId = 5,
                            Title = "Ganuchi Men Casual Olive Sandals",
                            UsageId = 1
                        },
                        new
                        {
                            Id = 44,
                            Active = true,
                            CategoryId = 2,
                            ColourId = 1,
                            GenderId = 3,
                            Image = "3790.jpg",
                            ImageURL = "http://assets.myntassets.com/v1/images/style/properties/2cbba1cd60b44011accb7c099a859ec4_images.jpg",
                            Price = 55.75,
                            ProductTypeId = 5,
                            SellerId = 4,
                            SubCategoryId = 3,
                            Title = "Converse Men's AS Canvas HI Black Shoe",
                            UsageId = 1
                        },
                        new
                        {
                            Id = 45,
                            Active = true,
                            CategoryId = 2,
                            ColourId = 7,
                            GenderId = 3,
                            Image = "33848.jpg",
                            ImageURL = "http://assets.myntassets.com/v1/images/style/properties/Puma-Men-Drift-Cat-Brown-Shoes_b37c89652031b205bcd19c36d6c686bd_images.jpg",
                            Price = 20.0,
                            ProductTypeId = 5,
                            SellerId = 4,
                            SubCategoryId = 3,
                            Title = "Puma Men Drift Cat Brown Shoes",
                            UsageId = 1
                        },
                        new
                        {
                            Id = 46,
                            Active = true,
                            CategoryId = 2,
                            ColourId = 14,
                            GenderId = 4,
                            Image = "44725.jpg",
                            ImageURL = "http://assets.myntassets.com/v1/images/style/properties/839c627c80dba9ac4412db3f35a52bb7_images.jpg",
                            Price = 30.850000000000001,
                            ProductTypeId = 10,
                            SellerId = 4,
                            SubCategoryId = 4,
                            Title = "Lotto Women Coral Elegant Flip Flops",
                            UsageId = 1
                        },
                        new
                        {
                            Id = 47,
                            Active = true,
                            CategoryId = 2,
                            ColourId = 1,
                            GenderId = 4,
                            Image = "16995.jpg",
                            ImageURL = "http://assets.myntassets.com/v1/images/style/properties/2e68ca2646690a4bf4ed092bf44cc6df_images.jpg",
                            Price = 24.989999999999998,
                            ProductTypeId = 14,
                            SellerId = 4,
                            SubCategoryId = 5,
                            Title = "Rocia Women Casual Black Sandal",
                            UsageId = 1
                        },
                        new
                        {
                            Id = 48,
                            Active = true,
                            CategoryId = 2,
                            ColourId = 15,
                            GenderId = 4,
                            Image = "13027.jpg",
                            ImageURL = "http://assets.myntassets.com/v1/images/style/properties/9d70af39b13503d1ae27c581dc5e711d_images.jpg",
                            Price = 30.850000000000001,
                            ProductTypeId = 8,
                            SellerId = 4,
                            SubCategoryId = 3,
                            Title = "Inc 5 Women Casual Gold Flats",
                            UsageId = 1
                        },
                        new
                        {
                            Id = 49,
                            Active = true,
                            CategoryId = 1,
                            ColourId = 1,
                            GenderId = 1,
                            Image = "39855.jpg",
                            ImageURL = "http://assets.myntassets.com/v1/images/style/properties/6fa45d21a0d6194932652bfcaf4c0e2b_images.jpg",
                            Price = 99.989999999999995,
                            ProductTypeId = 1,
                            SellerId = 1,
                            SubCategoryId = 1,
                            Title = "Product to test product suppression",
                            UsageId = 1
                        },
                        new
                        {
                            Id = 50,
                            Active = true,
                            CategoryId = 1,
                            ColourId = 1,
                            GenderId = 1,
                            Image = "39855.jpg",
                            ImageURL = "http://assets.myntassets.com/v1/images/style/properties/6fa45d21a0d6194932652bfcaf4c0e2b_images.jpg",
                            Price = 99.989999999999995,
                            ProductTypeId = 1,
                            SellerId = 1,
                            SubCategoryId = 1,
                            Title = "Product to test product suppression with appearence in order",
                            UsageId = 1
                        },
                        new
                        {
                            Id = 51,
                            Active = true,
                            CategoryId = 1,
                            ColourId = 1,
                            GenderId = 1,
                            Image = "39855.jpg",
                            ImageURL = "http://assets.myntassets.com/v1/images/style/properties/6fa45d21a0d6194932652bfcaf4c0e2b_images.jpg",
                            Price = 99.989999999999995,
                            ProductTypeId = 1,
                            SellerId = 1,
                            SubCategoryId = 1,
                            Title = "Product to test product suppression with disappearence in cart",
                            UsageId = 1
                        });
                });

            modelBuilder.Entity("INF27507_Boutique_En_Ligne.Models.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("pk_producttypes_id");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("ProductTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tshirts",
                            SubCategoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tops",
                            SubCategoryId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Skirts",
                            SubCategoryId = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Formal Shoes",
                            SubCategoryId = 3
                        },
                        new
                        {
                            Id = 5,
                            Name = "Casual Shoes",
                            SubCategoryId = 3
                        },
                        new
                        {
                            Id = 6,
                            Name = "Sports Shoes",
                            SubCategoryId = 3
                        },
                        new
                        {
                            Id = 7,
                            Name = "Flats",
                            SubCategoryId = 3
                        },
                        new
                        {
                            Id = 8,
                            Name = "Heels",
                            SubCategoryId = 3
                        },
                        new
                        {
                            Id = 9,
                            Name = "Shorts",
                            SubCategoryId = 2
                        },
                        new
                        {
                            Id = 10,
                            Name = "Flip Flops",
                            SubCategoryId = 4
                        },
                        new
                        {
                            Id = 11,
                            Name = "Kurtas",
                            SubCategoryId = 1
                        },
                        new
                        {
                            Id = 12,
                            Name = "Capris",
                            SubCategoryId = 2
                        },
                        new
                        {
                            Id = 13,
                            Name = "Sandals",
                            SubCategoryId = 5
                        },
                        new
                        {
                            Id = 14,
                            Name = "Sports Sandals",
                            SubCategoryId = 5
                        },
                        new
                        {
                            Id = 15,
                            Name = "Rompers",
                            SubCategoryId = 1
                        },
                        new
                        {
                            Id = 16,
                            Name = "Shirts",
                            SubCategoryId = 1
                        });
                });

            modelBuilder.Entity("INF27507_Boutique_En_Ligne.Models.Seller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id")
                        .HasName("pk_sellers_id");

                    b.ToTable("Sellers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Firstname = "Albert",
                            Lastname = "",
                            Username = "Albert"
                        },
                        new
                        {
                            Id = 2,
                            Firstname = "Amélie",
                            Lastname = "",
                            Username = "Amélie"
                        },
                        new
                        {
                            Id = 3,
                            Firstname = "Julie",
                            Lastname = "",
                            Username = "Julie"
                        },
                        new
                        {
                            Id = 4,
                            Firstname = "Xavier",
                            Lastname = "",
                            Username = "Xavier"
                        });
                });

            modelBuilder.Entity("INF27507_Boutique_En_Ligne.Models.SubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id")
                        .HasName("pk_subcategories_id");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Topwear"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Bottomwear"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Name = "Shoes"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Name = "Flip Flops"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Name = "Sandal"
                        });
                });

            modelBuilder.Entity("INF27507_Boutique_En_Ligne.Models.Usage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id")
                        .HasName("pk_usages_id");

                    b.ToTable("Usages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Casual"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Formal"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ethnic"
                        });
                });

            modelBuilder.Entity("INF27507_Boutique_En_Ligne.Models.Cart", b =>
                {
                    b.HasOne("INF27507_Boutique_En_Ligne.Models.Client", "Client")
                        .WithMany("Carts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("INF27507_Boutique_En_Ligne.Models.CartItem", b =>
                {
                    b.HasOne("INF27507_Boutique_En_Ligne.Models.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("INF27507_Boutique_En_Ligne.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("INF27507_Boutique_En_Ligne.Models.Order", b =>
                {
                    b.HasOne("INF27507_Boutique_En_Ligne.Models.Cart", "Cart")
                        .WithMany()
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("INF27507_Boutique_En_Ligne.Models.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("INF27507_Boutique_En_Ligne.Models.Product", b =>
                {
                    b.HasOne("INF27507_Boutique_En_Ligne.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("INF27507_Boutique_En_Ligne.Models.Colour", "Colour")
                        .WithMany()
                        .HasForeignKey("ColourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("INF27507_Boutique_En_Ligne.Models.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("INF27507_Boutique_En_Ligne.Models.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("INF27507_Boutique_En_Ligne.Models.Seller", "Seller")
                        .WithMany("Products")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("INF27507_Boutique_En_Ligne.Models.SubCategory", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("INF27507_Boutique_En_Ligne.Models.Usage", "Usage")
                        .WithMany()
                        .HasForeignKey("UsageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Colour");

                    b.Navigation("Gender");

                    b.Navigation("ProductType");

                    b.Navigation("Seller");

                    b.Navigation("SubCategory");

                    b.Navigation("Usage");
                });

            modelBuilder.Entity("INF27507_Boutique_En_Ligne.Models.ProductType", b =>
                {
                    b.HasOne("INF27507_Boutique_En_Ligne.Models.SubCategory", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("INF27507_Boutique_En_Ligne.Models.SubCategory", b =>
                {
                    b.HasOne("INF27507_Boutique_En_Ligne.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("INF27507_Boutique_En_Ligne.Models.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("INF27507_Boutique_En_Ligne.Models.Client", b =>
                {
                    b.Navigation("Carts");
                });

            modelBuilder.Entity("INF27507_Boutique_En_Ligne.Models.Seller", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
